apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-ootb-backstage
  annotations:
    github.com/project-slug: liatrio/demo-ootb-backstage
spec:
  type: website
  owner: tag-autogov
  lifecycle: experimental
